name: Test Automation WorkFlow

on:
  schedule:
    - cron: 30 07 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: Test logs
        path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Report as Artifacts
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
        name: html-report
        path: report.html

    - name: Test Execution Status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports
        cp -R screenshots/ public/extent-reports/screenshots
        ls -l
      

    - name: Deploy to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.6
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAT1 }}
        clean: true














  
